import {test,expect} from '@playwright/test'
test('draw, reshape, transform, save, export, and undo in one editor',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await expect(page.getByRole('status').first()).toContainText('Saved');const canvas=page.getByLabel('Glyph vector editor');await expect(canvas).toHaveCount(1);const box=(await canvas.boundingBox())!;
 await page.getByRole('button',{name:'Ellipse',exact:true}).click();await page.mouse.move(box.x+150,box.y+130);await page.mouse.down();await page.mouse.move(box.x+300,box.y+330,{steps:10});await page.mouse.up();await expect(page.getByRole('button',{name:/Outline 1/})).toBeVisible();await page.getByRole('button',{name:/Outline 1/}).click();await page.getByLabel('Rotation',{exact:true}).fill('15');await page.getByRole('button',{name:'Apply transform',exact:true}).click();await page.getByRole('button',{name:'Nodes',exact:true}).click();await expect(page.getByRole('button',{name:'Nodes',exact:true})).toHaveAttribute('aria-pressed','true');
 await page.getByLabel('Advance width').fill('700');await expect(page.getByRole('status').first()).toContainText('Saved');await page.reload();await expect(page.getByLabel('Advance width')).toHaveValue('700');await expect(page.getByRole('button',{name:/Outline 1/})).toBeVisible();await page.getByRole('button',{name:'Export font',exact:true}).click();const dl=page.waitForEvent('download');await page.getByRole('button',{name:'Download OTF',exact:true}).click();expect((await dl).suggestedFilename()).toMatch(/\.otf$/);await expect(page.getByRole('dialog')).toContainText('Download started');await page.getByRole('button',{name:'Close',exact:true}).click();expect(errors).toEqual([]);
 await page.screenshot({path:'test-results/studio-desktop.png',fullPage:true});
})
test('mobile has one editor and cancelled shapes leave no history',async({page})=>{await page.setViewportSize({width:390,height:844});await page.goto('/');await expect(page.getByLabel('Glyph vector editor')).toHaveCount(1);await page.getByRole('button',{name:'Rectangle',exact:true}).click();const b=(await page.getByLabel('Glyph vector editor').boundingBox())!;await page.mouse.move(b.x+90,b.y+90);await page.mouse.down();await page.mouse.move(b.x+200,b.y+250);await page.keyboard.press('Escape');await page.mouse.up();await expect(page.getByLabel('Undo',{exact:true})).toBeDisabled();await page.screenshot({path:'test-results/studio-mobile.png',fullPage:true})})
test('local projects and portable backups',async({page})=>{await page.goto('/');await expect(page.getByRole('status').first()).toContainText('Saved');await page.getByRole('button',{name:'Projects',exact:true}).click();await page.getByLabel('New project name').fill('Second font');await page.getByRole('button',{name:'New project',exact:true}).click();await expect(page.getByLabel('Font name')).toHaveValue('Second font');await expect(page.getByRole('status').first()).toContainText('Saved');await page.getByRole('button',{name:'Projects',exact:true}).click();const download=page.waitForEvent('download');await page.getByRole('button',{name:'Download editable backup'}).click();expect((await download).suggestedFilename()).toBe('Second font.inkfont');await expect(page.getByRole('dialog')).toContainText('Untitled handwriting')})

test('freehand becomes editable vectors and node drags are undoable',async({page})=>{
 await page.goto('/');await expect(page.getByRole('status').first()).toContainText('Saved');const canvas=page.getByLabel('Glyph vector editor'),b=(await canvas.boundingBox())!;
 await page.getByRole('button',{name:'Brush',exact:true}).click();await page.mouse.move(b.x+160,b.y+150);await page.mouse.down();for(let i=1;i<=12;i++)await page.mouse.move(b.x+160+i*10,b.y+150+Math.sin(i/3)*70);await page.mouse.up();await expect(page.getByRole('button',{name:/Outline 1/})).toBeVisible({timeout:20000});await page.getByRole('button',{name:/Outline 1/}).click();await page.getByRole('button',{name:'Nodes',exact:true}).click();await expect(page.getByRole('button',{name:'Nodes',exact:true})).toHaveAttribute('aria-pressed','true');await page.keyboard.press('Tab');await page.keyboard.press('ArrowRight');await expect(page.getByLabel('Undo',{exact:true})).toBeEnabled();await page.getByLabel('Undo',{exact:true}).click();await page.getByLabel('Redo',{exact:true}).click();await expect(page.getByRole('status').first()).toContainText('Saved');
})
test('image tracing is local and keeps a counter',async({page})=>{
 await page.goto('/');await expect(page.getByRole('status').first()).toContainText('Saved');const png=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=100;c.height=100;const x=c.getContext('2d')!;x.fillStyle='white';x.fillRect(0,0,100,100);x.fillStyle='black';x.fillRect(10,10,80,80);x.fillStyle='white';x.fillRect(30,30,40,40);return c.toDataURL().split(',')[1]});await page.getByRole('button',{name:'Import',exact:true}).click();await page.getByLabel('Import file').setInputFiles({name:'ring.png',mimeType:'image/png',buffer:Buffer.from(png,'base64')});await page.getByRole('button',{name:'Auto-trace image',exact:true}).click();await expect(page.getByRole('dialog')).toContainText('2 contours',{timeout:20000});await page.getByRole('button',{name:'Accept vectors & reference',exact:true}).click();await expect(page.getByRole('button',{name:/Outline 1/})).toBeVisible();await expect(page.getByRole('status').first()).toContainText('Saved');await page.reload();await expect(page.getByRole('button',{name:/Outline 1/})).toBeVisible();
})
